//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedSource.POI.sitecore_modules.Shell.Editors.Website.Point_Of_Interest_Map {
    
    
    public partial class PointOfInterestMap {
    }
}
